#define IDH_PROPERTYEDITOR.PRG  13
#define IDH_BENEFITS_OF_THE_REPLACEMENT_DIALOG  7
#define IDH_SFPROPERTYEDITOR  14
#define IDH_SFPROPERTYEDITORTOGGLE  15
#define IDH_PROPERTY_EDITOR  9
#define IDH_SFPROPERTYEDITORENUMERATED  16
#define IDH_LOCALIZING_THE_NEW_PROPERTY/METHOD_REPLACEMENT_DIALOG  21
#define IDH_HOW_IT_WORKS  3
#define IDH_OTHER_PROPERTY_EDITOR_THOUGHTS  17
#define IDH_MENUHIT  4
#define IDH_MORE_ABOUT_MENUHIT  5
#define IDH_THE_REPLACEMENT_DIALOG  6

